
import type { Metadata } from "next";
import { Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Chatbot from "@/components/Chabtox";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GYM APP",
  description: "Generated by create next app",
};

export default function RootLayout({
 

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar  />
        {children}
        <Footer />
        <Chatbot /> {/* Ajoute le Chatbot ici */}
        </body>
    </html>
  );
}
